# Change these first
owner: BeansHosting-net # Your GitHub organization or username, where this repository lives
repo: status.beanshosting.net # The name of this repository

sites:
  - name: Beans Hosting Website
    url: https://beanshosting.net
    icon: https://icon.horse/icon/beanshosting.net
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Node 1 (Miami, USA)
    check: "tcp-ping"
    url: $NODE_1_USA_IP
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.beanshosting.net
  # baseUrl: /your-repo-name
  logoUrl: https://icon.horse/icon/beanshosting.net
  name: Beans Hosting Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
#workflowSchedule:
#  graphs: "0 */24 * * *"
#  responseTime: "*/5 * * * *"
#  staticSite: "0 1 * * *"
#  summary: "0 0 * * *"
#  updateTemplate: "0 0 * * *"
#  updates: "*/5 * * * *"
#  uptime: "*/5 * * * *"
